### ISSUE TITLE
Provider com.bea.xml.stream.EventFactory not found

### ISSUE THREAD

**Issue by Kolyall** [SUPERCILEX/poi-android#11]
```
 org.apache.poi.javax.xml.stream.FactoryConfigurationError: Provider com.bea.xml.stream.EventFactory not found
        at org.apache.poi.javax.xml.stream.FactoryFinder.newInstance(FactoryFinder.java:72)
        at org.apache.poi.javax.xml.stream.FactoryFinder.find(FactoryFinder.java:178)
        at org.apache.poi.javax.xml.stream.FactoryFinder.find(FactoryFinder.java:92)
        at org.apache.poi.javax.xml.stream.XMLEventFactory.newInstance(XMLEventFactory.java:30)
        at org.apache.poi.openxml4j.opc.internal.marshallers.PackagePropertiesMarshaller.<clinit>(PackagePropertiesMarshaller.java:41)
        at org.apache.poi.openxml4j.opc.OPCPackage.init(OPCPackage.java:161)
        at org.apache.poi.openxml4j.opc.OPCPackage.<init>(OPCPackage.java:141)
        at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:72)
        at org.apache.poi.openxml4j.opc.OPCPackage.create(OPCPackage.java:394)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.newPackage(XSSFWorkbook.java:480)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:247)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:239)
```

gradle:
```
compileOnly ("org.apache.poi:poi-ooxml:3.17"){
        exclude group: "org.apache.xmlbeans", module: "xmlbeans"
    }
    compileOnly ("org.apache.poi:poi:3.17"){
        exclude group: "org.apache.xmlbeans", module: "xmlbeans"
    }

    implementation "com.github.SUPERCILEX.poi-android:poi:3.17"
```

**Comment by SUPERCILEX** [comment]
See #5

**Comment by Kolyall** [comment]
Resolved:
```
 System.setProperty(
                    "org.apache.poi.javax.xml.stream.XMLInputFactory",
                    "com.fasterxml.aalto.stax.InputFactoryImpl"
            );
            System.setProperty(
                    "org.apache.poi.javax.xml.stream.XMLOutputFactory",
                    "com.fasterxml.aalto.stax.OutputFactoryImpl"
            );
            System.setProperty(
                    "org.apache.poi.javax.xml.stream.XMLEventFactory",
                    "com.fasterxml.aalto.stax.EventFactoryImpl"
            );
```

**Comment by Kolyall** [comment]
@SUPERCILEX doesn't work with v4.1.2
I pulled the repo, and update the versions to 
`org.apache.poi:poi:4.1.2`
`org.apache.poi:poi-ooxml:4.1.2`

And the error occurs
```
 Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/poi/javax/xml/stream/XMLStreamReader;
        at org.apache.xmlbeans.XmlBeans.buildStreamToNodeMethod(XmlBeans.java:251)
        at org.apache.xmlbeans.XmlBeans.<clinit>(XmlBeans.java:138)
        at org.apache.xmlbeans.XmlBeans.typeLoaderForClassLoader(XmlBeans.java:719)
        at org.openxmlformats.schemas.spreadsheetml.x2006.main.SstDocument$Factory.getTypeLoader(Unknown Source:25)
        at org.openxmlformats.schemas.spreadsheetml.x2006.main.SstDocument$Factory.parse(Unknown Source:0)
        at org.apache.poi.xssf.model.SharedStringsTable.readFrom(SharedStringsTable.java:123)
        at org.apache.poi.xssf.model.SharedStringsTable.<init>(SharedStringsTable.java:111)
        at org.apache.poi.xssf.usermodel.-$$Lambda$CKJ44EDIO-92rB6cwbMPKp5su5A.init(Unknown Source:2)
        at org.apache.poi.ooxml.POIXMLFactory.createDocumentPart(POIXMLFactory.java:61)
        at org.apache.poi.ooxml.POIXMLDocumentPart.read(POIXMLDocumentPart.java:684)
        at org.apache.poi.ooxml.POIXMLDocument.load(POIXMLDocument.java:180)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:288)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:309)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.poi.javax.xml.stream.XMLStreamReader" on path: DexPathList[[zip file "/data/app/~~SX-9TVY48SmzQ730WFOrSw==/com.nfcrfidreader-pldQhoZN1DcENq6LURuKLg==/base.apk"],nativeLibraryDirectories=[/data/app/~~SX-9TVY48SmzQ730WFOrSw==/com.nfcrfidreader-pldQhoZN1DcENq6LURuKLg==/lib/x86, /system/lib, /system_ext/lib, /product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 65 more
2020-10-09 21:44:31.791 23949-23949/com.nfcrfidreader I/Process: Sending signal. PID: 23949 SIG: 9

```

```
class TheApplication : Application(){

    override fun onCreate() {
        super.onCreate()
        System.setProperty(
            "org.apache.poi.javax.xml.stream.XMLInputFactory",
            "com.fasterxml.aalto.stax.InputFactoryImpl"
        )
        System.setProperty(
            "org.apache.poi.javax.xml.stream.XMLOutputFactory",
            "com.fasterxml.aalto.stax.OutputFactoryImpl"
        )
        System.setProperty(
            "org.apache.poi.javax.xml.stream.XMLEventFactory",
            "com.fasterxml.aalto.stax.EventFactoryImpl"
        )
    }
}
```
